disabled_rules: # rule identifiers to exclude from running
  - identifier_name
  - nesting
  - function_parameter_count
  - trailing_whitespace
  - file_length
opt_in_rules: # some rules are only opt-in
  - control_statement
  - explicit_enum_raw_value
  - empty_count
  - trailing_newline
  - force_unwrapping
  - colon
  - comma
included: # paths to include during linting. `--path` is ignored if present.
  - SuppsTrack/Data
  - SuppsTrack/UI
  - SuppsTrack/DI+Others.swift
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Assets
  - GoogleService-Info
  - .swiftlint.yml
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly. Give warning only for force casting

force_try:
  severity: warning # explicitly. Give warning only for force try

type_body_length:
  - 300 # warning
  - 400 # error
