only_rules: # some rules are only opt-in
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - vertical_whitespace_between_cases
  - closure_spacing
  - control_statement
  - empty_count
  - trailing_newline
  - force_unwrapping
  - colon
  - comma
included: # paths to include during linting. `--path` is ignored if present.
  - SuppsTrack/Data
  - SuppsTrack/UI
  - SuppsTrack/DI+Others.swift
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Assets
  - GoogleService-Info
  - .swiftlint.yml
